In [ ]:
import pandas as pd

bangalore_df = pd.read_excel('Dataset/bangalore_cars.xlsx')
jaipur_df =  pd.read_excel('Dataset/jaipur_cars.xlsx')
chennai_df =  pd.read_excel('Dataset/chennai_cars.xlsx')
hyderabad_df =  pd.read_excel('Dataset/hyderabad_cars.xlsx')
kolkata_df =  pd.read_excel('Dataset/kolkata_cars.xlsx')
delhi_df =  pd.read_excel('Dataset/delhi_cars.xlsx')

In [15]:
# Adding the Column for the DataSet to mention the City

chennai_df['City'] = 'Chennai'
delhi_df['City'] = 'Delhi'
hyderabad_df['City'] = 'Hyderabad'
jaipur_df['City'] = 'Jaipur'
kolkata_df['City'] = 'Kolkata'
bangalore_df['City'] = 'Bangalore'

In [12]:
jaipur_df

,new_car_detail,new_car_overview,new_car_feature,new_car_specs,car_links,City
0,"{'it': 0, 'ft': 'Diesel', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,Jaipur
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...,Jaipur
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,Jaipur
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...,Jaipur
4,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,Jaipur
...,...,...,...,...,...,...
1115,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,Jaipur
1116,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Low...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,Jaipur
1117,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,Jaipur
1118,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Low...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,Jaipur
1119,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,Jaipur

In [6]:
df1 = pd.concat([bangalore_df,chennai_df],ignore_index = True)
df2 = pd.concat([delhi_df,hyderabad_df],ignore_index = True)
df3 = pd.concat([jaipur_df,kolkata_df], ignore_index = True)
df4 = pd.concat([df1,df2],ignore_index = True)
final_df = pd.concat([df4,df3],ignore_index = True)
final_df.shape

(8369, 6)

In [7]:
final_df

,new_car_detail,new_car_overview,new_car_feature,new_car_specs,car_links,City
0,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,NaN
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...,NaN
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,NaN
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...,NaN
4,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,NaN
...,...,...,...,...,...,...
8364,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,Kolkata
8365,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,Kolkata
8366,"{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,Kolkata
8367,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,Kolkata
8368,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,Kolkata

In [22]:
import pandas as pd

df = pd.DataFrame(final_df['new_car_detail'])
Json_normalized = pd.json_normalize(df['new_car_detail'].apply(eval))
# Json_normalized = pd.json_normalize(df)
df = pd.concat([df.drop(columns=["new_car_detail"]), Json_normalized], axis=1)

print(df)

      it      ft         bt        km transmission  ownerNo      owner  \
0      0  Petrol  Hatchback  1,20,000       Manual        3  3rd Owner
1      0  Petrol        SUV    32,706       Manual        2  2nd Owner
2      0  Petrol  Hatchback    11,949       Manual        1  1st Owner
3      0  Petrol      Sedan    17,794       Manual        1  1st Owner
4      0  Diesel        SUV    60,000       Manual        1  1st Owner
...   ..     ...        ...       ...          ...      ...        ...
8364   0  Petrol  Hatchback    10,000       Manual        1  1st Owner
8365   0  Petrol  Hatchback  1,20,000       Manual        1  1st Owner
8366   0  Petrol      Sedan    50,000    Automatic        3  3rd Owner
8367   0  Petrol  Hatchback    40,000       Manual        1  1st Owner
8368   0  Diesel        SUV  1,20,000       Manual        2  2nd Owner

                oem                  model  modelYear  centralVariantId  \
0            Maruti         Maruti Celerio       2015              3979
1              Ford          Ford Ecosport       2018              6087
2              Tata             Tata Tiago       2018              2983
3           Hyundai          Hyundai Xcent       2014              1867
4            Maruti     Maruti SX4 S Cross       2015              4277
...             ...                    ...        ...               ...
8364         Maruti         Maruti Celerio       2022              8682
8365         Maruti        Maruti Alto 800       2014              3943
8366  Mercedes-Benz  Mercedes-Benz C-Class       2011              4672
8367         Maruti            Maruti Ritz       2012              4144
8368        Renault         Renault Duster       2017              5048

                   variantName        price priceActual priceSaving  \
0                          VXI     ₹ 4 Lakh
1     1.5 Petrol Titanium BSIV  ₹ 8.11 Lakh
2              1.2 Revotron XZ  ₹ 5.85 Lakh
3           1.2 Kappa S Option  ₹ 4.62 Lakh
4                DDiS 200 Zeta  ₹ 7.90 Lakh
...                        ...          ...         ...         ...
8364                  ZXI BSVI  ₹ 5.10 Lakh
8365                       LXI  ₹ 1.80 Lakh
8366        C 200 CGI Elegance  ₹ 5.50 Lakh
8367                       ZXi  ₹ 1.40 Lakh
8368      110PS Diesel RxZ AWD     ₹ 5 Lakh

     priceFixedText                                trendingText.imgUrl  \
0              None  https://stimg.cardekho.com/used-cars/common/ic...
1              None  https://stimg.cardekho.com/used-cars/common/ic...
2              None  https://stimg.cardekho.com/used-cars/common/ic...
3              None  https://stimg.cardekho.com/used-cars/common/ic...
4              None  https://stimg.cardekho.com/used-cars/common/ic...
...             ...                                                ...
8364           None  https://stimg.cardekho.com/used-cars/common/ic...
8365           None  https://stimg.cardekho.com/used-cars/common/ic...
8366           None  https://stimg.cardekho.com/used-cars/common/ic...
8367           None  https://stimg.cardekho.com/used-cars/common/ic...
8368           None  https://stimg.cardekho.com/used-cars/common/ic...

     trendingText.heading                    trendingText.desc
0           Trending Car!  High chances of sale in next 6 days
1           Trending Car!  High chances of sale in next 6 days
2           Trending Car!  High chances of sale in next 6 days
3           Trending Car!  High chances of sale in next 6 days
4           Trending Car!  High chances of sale in next 6 days
...                   ...                                  ...
8364        Trending Car!  High chances of sale in next 6 days
8365        Trending Car!  High chances of sale in next 6 days
8366        Trending Car!  High chances of sale in next 6 days
8367        Trending Car!  High chances of sale in next 6 days
8368        Trending Car!  High chances of sale in next 6 days

[8369 rows x 19 columns]

In [23]:
df

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,centralVariantId,variantName,price,priceActual,priceSaving,priceFixedText,trendingText.imgUrl,trendingText.heading,trendingText.desc
0,0,Petrol,Hatchback,"1,20,000",Manual,3,3rd Owner,Maruti,Maruti Celerio,2015,3979,VXI,₹ 4 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1,0,Petrol,SUV,"32,706",Manual,2,2nd Owner,Ford,Ford Ecosport,2018,6087,1.5 Petrol Titanium BSIV,₹ 8.11 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
2,0,Petrol,Hatchback,"11,949",Manual,1,1st Owner,Tata,Tata Tiago,2018,2983,1.2 Revotron XZ,₹ 5.85 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
3,0,Petrol,Sedan,"17,794",Manual,1,1st Owner,Hyundai,Hyundai Xcent,2014,1867,1.2 Kappa S Option,₹ 4.62 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
4,0,Diesel,SUV,"60,000",Manual,1,1st Owner,Maruti,Maruti SX4 S Cross,2015,4277,DDiS 200 Zeta,₹ 7.90 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8364,0,Petrol,Hatchback,"10,000",Manual,1,1st Owner,Maruti,Maruti Celerio,2022,8682,ZXI BSVI,₹ 5.10 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
8365,0,Petrol,Hatchback,"1,20,000",Manual,1,1st Owner,Maruti,Maruti Alto 800,2014,3943,LXI,₹ 1.80 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
8366,0,Petrol,Sedan,"50,000",Automatic,3,3rd Owner,Mercedes-Benz,Mercedes-Benz C-Class,2011,4672,C 200 CGI Elegance,₹ 5.50 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
8367,0,Petrol,Hatchback,"40,000",Manual,1,1st Owner,Maruti,Maruti Ritz,2012,4144,ZXi,₹ 1.40 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
8368,0,Diesel,SUV,"1,20,000",Manual,2,2nd Owner,Renault,Renault Duster,2017,5048,110PS Diesel RxZ AWD,₹ 5 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days